#!/usr/bin/env python

import requests
from bs4 import BeautifulSoup as bs
addr = "http://historical.elections.virginia.gov/elections/search/year_from:1924/year_to:2016/office_id:1/stage:General"
resp = requests.get(addr)
soup = bs(resp.content, "html.parser")

s = soup.find_all("tr" , "election_item")

for tr in s:
  id = (tr['id'][-5:])
  year = tr.find("td").contents[0]
  ELECTION_ID = ('{} {}' .format(year, id))

  print(ELECTION_ID)
