#!/usr/bin/env python

import requests
from bs4 import BeautifulSoup as bs
addr = "http://historical.elections.virginia.gov/elections/search/year_from:1924/year_to:2016/office_id:1/stage:General"
resp = requests.get(addr)
soup = bs(resp.content, "html.parser")

s = soup.find_all("tr" , "election_item")

l = []
for tr in s:
  id = (tr['id'][-5:])
  year = tr.find("td").contents[0]
  ELECTION_ID = ('{} {}' .format(year, id))
  l.append([year, id])
  print(ELECTION_ID)



for x in l:
    addr = "http://historical.elections.virginia.gov/elections/download/{}/precincts_include:0/".format(x[1])
    resp = requests.get(addr)


    file_name = x[0] + ".csv"
    with open(file_name, "w") as out:
        out.write(resp.text)
